name: Deploy to Compute Engine
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t qais004/hackjkt-ml:latest .
          docker push qais004/hackjkt-ml:latest

      - name: Deploy to Compute Engine
        uses: appleboy/ssh-action@master
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PK }}
          envs: GOOGLE_APPLICATION_CREDENTIALS
          script: |
            echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > /tmp/google-credentials.json
            docker pull qais004/hackjkt-ml:latest
            docker stop hackjkt-ml
            docker rm hackjkt-ml
            docker run -d \
            --name hackjkt-ml \
            -p 5000:3000 \
            -e GOOGLE_APPLICATION_CREDENTIALS="/credentials/google-credentials.json" \
            -v /tmp/google-credentials.json:/credentials/google-credentials.json \
            qais004/hackjkt-ml